language: cpp
dist: bionic

before_install:
  - sudo apt-get -y install libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev

script:
  - ./configure
  - make
