language: cpp
dist: bionic

install:
  - pyenv global 3.7
  - pip install conan
  - conan user
  - sudo apt-get -y install libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
  - conan install --file ./.conanfile

script:
  - ./configure
  - make

notifications:
  webhooks:
    urls:
      - http://savageking.io:12811/travis
    on_success: always
    on_failure: always 
    on_start:   always 
    on_cancel:  always
    on_error:   always
