#ifndef __ANIMATION_FILE_SHOEBOX_HPP__
#define __ANIMATION_FILE_SHOEBOX_HPP__

/*
 * Support for XML files generated by [ShoeBox](http://renderhjs.net/shoebox/)
 */

#include "Engine.hpp"
#include "AnimationFileBase.hpp"

namespace EvelEngine {
    class AnimationFileShoeBox : public AnimationFileBase {
        public:
            AnimationFileShoeBox(const std::string& xmlfile);
            ~AnimationFileShoeBox();
            std::vector<Frame> unmarshal();
            std::string marshal();
        protected:
            bool isExistingTag(const std::string& tag) const;
            void addIndexToTag(const std::string& tag, int index);
            void createNewTag(const std::string& tag, int index);
            const std::string purifyTag(const std::string& tag) const;
            bool isTagHasNumbers(const std::string& tag) const;
            void appendFrame(int index, int x, int y, int w, int h);
            void addSpriteFile(const std::string& spritefile);
        private:
            Log* _log;
    };
}

#endif